
model: "cnn_dense"

paths:
  data_path: /staff/tord/Workspace/arces_classification/data
  #data_path: /nobackup/tord/gpu-test-tord/data
  labels: ["explosion", "noise", "earthquake"]
  output_folder: /staff/tord/Workspace/arces_classification/output
  data_csv: /staff/tord/Workspace/arces_classification/output/data.csv
  model_save_folder: /staff/tord/Workspace/arces_classification/output/models
  logs_folder: /staff/tord/Workspace/arces_classification/output/logs
  predictions_folder: /staff/tord/Workspace/arces_classification/output/folder
  plots_folder: /staff/tord/Workspace/arces_classification/output
  loaded_path: /staff/tord/Workspace/arces_classification/data/loaded/
  

data:
  num_classes: 3
  load_filtered: True
  what_to_load: ["train", "val"]
  train_prop: 0.8
  val_prop: 0.6
  first_date: "1998-10-01"

filters:
  use_filters: True
  detrend: True
  taper: True
  taper_max_percentage: 0.05
  highpass_or_bandpass: bandpass
  band_kwargs:
    min: 2
    max: 8
  high_kwargs:
    high_freq: 1.0

callbacks:
  early_stopping_patience: 7
  umap_interval: 5

scaling:
  scaler_type: minmax
  per_channel: False
  global_or_local: local

augment:
  zero_channel: True
  zero_channel_kwargs:
    prob: 0.1
  add_gap: True
  add_gap_kwargs:
    prob: 0.1
    max_size: 0.01
  add_noise: True
  add_noise_kwargs:
    prob: 0.1
    noise_std: 0.1
  taper: False
  taper_kwargs:
    prob: 1
    alpha: 0.04

optimizer:
  max_epochs: 150
  batch_size: 32
  optimizer: adam
  optimizer_kwargs:
    lr: 0.0001
    weight_decay: 0.0001





